task move(int enemyIdx) {
    let baseX, baseY = getPosition(enemyIdx);
    let goesLeft = true;
    let x = baseX;
    let y = baseY;

    loop {
    	if(goesLeft) {
    		x = x - 1f;
    	} else {
    		x = x + 1f;
    	}

        setPosition(enemyIdx, x, y);
        yield;

        if(goesLeft and (x < (baseX - 100f))) {
    		goesLeft = false;
    	}

    	if(!goesLeft and (x > (baseX + 100f))) {
    		goesLeft = true;
    	}
    }
}