import "data/script/rainbow.gr"
import "data/script/patterns.gr"

main {
	playerShots();

	int enemyIdx = 0;
	array posx = [500f, 600f, 700f, 800f, 900f];

	Enemy medicine = spawnEnemy("medicine", 7500f, -80f);
	moveRandom(medicine);
	yield;

	loop (5) {
		float x = posx[enemyIdx] as float;

		Enemy enemy = spawnEnemy("enemy2", x, -150f);
		movePatrol(enemy);
		yield;
		fireCircle(enemy);
		yield;
		enemyIdx++;
	}

	Enemy ghost = spawnEnemy("enemy3", 1500f, -300f);
	moveToPlayer(ghost);
}