import "data/script/rainbow.gr"
import "data/script/skull.gr"
import "data/script/medicine.gr"

main {
	playerShots();

	int enemyIdx = 0;
	array posx = [500f, 600f, 700f, 800f, 900f];

	Enemy medicine = spawnEnemy("medicine", 2000f, -80f);
	printEnemyPtr(medicine);
	randomMove(medicine);

	loop (5) {
		float x = posx[enemyIdx] as float;

		Enemy enemy = spawnEnemy("enemy2", x, -150f);
		moveSkull(enemy);
		fireCircle(enemy);
		enemyIdx++;
	}

	printEnemyPtr(medicine);
}